//! SSCCS core concepts in RISC-V assembly — with pure-Rust software fallback.
//!
//! Each concept has its own `.S` file under `asm/`:
//! - `observe_full.S`   — Observation pipeline (constraints, composition, projectors)
//! - `collapse.S`       — Multi-segment reduction (sum, min, max, product, weighted)
//! - `field_update.S`   — Field mutation (constraint add/remove, transition update)
//! - `scheme_layout.S`  — Coordinate-to-address mapping (linear, row-major, z-order)
//! - `scheme_adjacency.S` — Structural neighbor discovery (grid, manhattan, graph)
//!
//! The `asm_data` module (generated by `build.rs`) exposes `.8byte` constants
//! from each file as a submodule (e.g. `asm_data::observe_full::SEG_0`).
//!
//! Validation strategy:
//!   RISC-V target: actual assembly via `global_asm!`
//!   Other targets:  pure-Rust fallback with identical logic
//!   Golden anchor:  test reads GOLDEN_* from `.S` files and verifies correctness
//!
//! This ensures changing a `.S` file forces updating its golden anchors,
//! which forces updating the Rust tests — keeping both in sync.

#![allow(dead_code)]

pub const REJECT_SENTINEL: i64 = i64::MIN;
pub type ConstraintFn = unsafe extern "C" fn(*const i64) -> u32;
pub type ProjectorFn = unsafe extern "C" fn(*const i64) -> i64;
pub type ReducerFn = unsafe extern "C" fn(*const i64, usize) -> i64;

// ============================================================================
// 1. OBSERVE — Full observation pipeline
// ============================================================================

#[cfg(target_arch = "riscv64")]
global_asm!(include_str!("../asm/observe_full.S"));

#[cfg(target_arch = "riscv64")]
extern "C" {
    // Constraints
    fn ck_even(coord: *const i64) -> u32;
    fn ck_range_0_10(coord: *const i64) -> u32;
    fn ck_range(coord: *const i64, min: i64, max: i64) -> u32;
    fn ck_eq_val(coord: *const i64, target: i64) -> u32;
    fn ck_gt(coord: *const i64, threshold: i64) -> u32;
    fn ck_even_w(coord: *const i64) -> u32;
    fn ck_range_w(coord: *const i64) -> u32;
    // Composition
    fn compose_and_fast(fa: ConstraintFn, fb: ConstraintFn, coord: *const i64) -> u32;
    fn compose_or_fast(fa: ConstraintFn, fb: ConstraintFn, coord: *const i64) -> u32;
    fn compose_intersect(fa: ConstraintFn, fb: ConstraintFn, coord: *const i64) -> u32;
    fn compose_union(fa: ConstraintFn, fb: ConstraintFn, coord: *const i64) -> u32;
    fn compose_product_2d(fa: ConstraintFn, fb: ConstraintFn, coord: *const i64) -> u32;
    // Projectors
    fn proj_id(coord: *const i64) -> i64;
    fn proj_sum2d(coord: *const i64) -> i64;
    fn proj_sum3d(coord: *const i64) -> i64;
    fn proj_parity(coord: *const i64) -> i64;
    fn proj_negate(coord: *const i64) -> i64;
    // Pipeline
    fn observe(field_fn: ConstraintFn, coord: *const i64, proj_fn: ProjectorFn) -> i64;
    fn observe_batch(
        field_fn: ConstraintFn,
        coords: *const *const i64,
        count: usize,
        proj_fn: ProjectorFn,
        out: *mut i64,
    );
    fn run_narrow();
    fn run_broad();
    // Static segments
    static SEG_0: i64;
    static SEG_1: i64;
    static SEG_2: i64;
    static SEG_3: i64;
    static SEG_4: i64;
    static BATCH_COORDS: [*const i64; 5];
    static NARROW_RESULTS: [i64; 5];
    static BROAD_RESULTS: [i64; 5];
    static SEG_3D_A: [i64; 3];
    static SEG_3D_B: [i64; 3];
}

// ============================================================================
// 2. COLLAPSE — Multi-segment reduction
// ============================================================================

#[cfg(target_arch = "riscv64")]
global_asm!(include_str!("../asm/collapse.S"));

#[cfg(target_arch = "riscv64")]
extern "C" {
    fn collapse_sum(coords: *const i64, count: usize) -> i64;
    fn collapse_min(coords: *const i64, count: usize) -> i64;
    fn collapse_max(coords: *const i64, count: usize) -> i64;
    fn collapse_product(coords: *const i64, count: usize) -> i64;
    fn collapse_count(results: *const i64, count: usize, sentinel: i64) -> usize;
    fn collapse_weighted_sum(coords: *const i64, weights: *const i64, count: usize) -> i64;
    fn collapse_weighted_avg(coords: *const i64, weights: *const i64, count: usize) -> i64;
    fn collapse(coords: *const i64, count: usize, reducer: ReducerFn) -> i64;
    fn collapse_batch(
        groups: *const *const i64,
        counts: *const usize,
        num_groups: usize,
        reducer: ReducerFn,
        out: *mut i64,
    );
}

// ============================================================================
// 3. FIELD_UPDATE — Constraint & transition mutation
// ============================================================================

#[cfg(target_arch = "riscv64")]
global_asm!(include_str!("../asm/field_update.S"));

#[cfg(target_arch = "riscv64")]
extern "C" {
    fn field_add_constraint(field: *mut u8, constraint_fn: usize, constraint_id: u32) -> i32;
    fn field_remove_constraint(field: *mut u8, constraint_id: u32) -> i32;
    fn field_clear(field: *mut u8);
    fn field_add_transition(field: *mut u8, from_id: i64, to_id: i64, weight: i64) -> i32;
    fn field_update_weight(field: *mut u8, from_id: i64, to_id: i64, new_weight: i64) -> i32;
    fn field_get_transitions(field: *mut u8, from_id: i64, out: *mut u8) -> usize;
}

// ============================================================================
// 4. SCHEME_LAYOUT — Coordinate-to-address mapping
// ============================================================================

#[cfg(target_arch = "riscv64")]
global_asm!(include_str!("../asm/scheme_layout.S"));

#[cfg(target_arch = "riscv64")]
extern "C" {
    fn layout_linear_1d(coord: i64, stride: i64) -> i64;
    fn layout_linear_nd(coords: *const i64, strides: *const i64, dims: u32) -> i64;
    fn layout_row_major_2d(x: i64, y: i64, width: i64, elem_size: i64) -> i64;
    fn layout_row_major_3d(x: i64, y: i64, z: i64, width: i64, height: i64, elem_size: i64) -> i64;
    fn layout_col_major_2d(x: i64, y: i64, height: i64, elem_size: i64) -> i64;
    fn morton_encode_2d(x: i64, y: i64) -> i64;
    fn layout_zorder_2d(x: i64, y: i64, elem_size: i64) -> i64;
    fn layout_batch(
        coord_sets: *const *const i64,
        strides: *const i64,
        count: usize,
        layout_fn: usize,
        out: *mut i64,
    );
}

// ============================================================================
// 5. SCHEME_ADJACENCY — Structural neighbor discovery
// ============================================================================

#[cfg(target_arch = "riscv64")]
global_asm!(include_str!("../asm/scheme_adjacency.S"));

#[cfg(target_arch = "riscv64")]
extern "C" {
    fn adj_grid_4(
        x: i64,
        y: i64,
        min_x: i64,
        max_x: i64,
        min_y: i64,
        max_y: i64,
        out: *mut i64,
    ) -> usize;
    fn adj_grid_8(
        x: i64,
        y: i64,
        min_x: i64,
        max_x: i64,
        min_y: i64,
        max_y: i64,
        out: *mut i64,
    ) -> usize;
    fn adj_manhattan_1d(
        coord: i64,
        distance: u32,
        min_coord: i64,
        max_coord: i64,
        out: *mut i64,
    ) -> usize;
    fn adj_graph_edges(
        edge_pairs: *const i64,
        num_edges: u32,
        from_id: i64,
        out: *mut i64,
    ) -> usize;
    fn adj_batch(
        coords: *const i64,
        num_coords: usize,
        adj_fn: usize,
        out: *mut i64,
        capacity: usize,
    ) -> usize;
}

// ============================================================================
// Pure-Rust fallback — logic identical to RISC-V asm. Tested on CI.
// ============================================================================

#[cfg(not(target_arch = "riscv64"))]
pub mod fallback {
    // ── Observe: constraints ──
    pub fn ck_even(v: i64) -> u32 {
        ((v & 1) ^ 1) as u32
    }
    pub fn ck_range_0_10(v: i64) -> u32 {
        (v >= 0 && v <= 10) as u32
    }
    pub fn ck_range(v: i64, lo: i64, hi: i64) -> u32 {
        (v >= lo && v <= hi) as u32
    }
    pub fn ck_eq_val(v: i64, t: i64) -> u32 {
        (v == t) as u32
    }
    pub fn ck_gt(v: i64, t: i64) -> u32 {
        (v > t) as u32
    }
    pub fn compose_and(fa: fn(i64) -> u32, fb: fn(i64) -> u32, v: i64) -> u32 {
        fa(v) & fb(v)
    }
    pub fn compose_or(fa: fn(i64) -> u32, fb: fn(i64) -> u32, v: i64) -> u32 {
        fa(v) | fb(v)
    }
    pub fn proj_id(v: i64) -> i64 {
        v
    }
    pub fn proj_sum2d(a: i64, b: i64) -> i64 {
        a + b
    }
    pub fn proj_sum3d(a: i64, b: i64, c: i64) -> i64 {
        a + b + c
    }
    pub fn proj_parity(v: i64) -> i64 {
        v & 1
    }
    pub fn proj_negate(v: i64) -> i64 {
        -v
    }
    pub fn observe(field: fn(i64) -> u32, coord: i64, proj: fn(i64) -> i64) -> i64 {
        if field(coord) != 0 {
            proj(coord)
        } else {
            i64::MIN
        }
    }

    // ── Collapse ──
    pub fn collapse_sum(coords: &[i64]) -> i64 {
        coords.iter().sum()
    }
    pub fn collapse_min(coords: &[i64]) -> i64 {
        coords.iter().copied().min().unwrap_or(i64::MAX)
    }
    pub fn collapse_max(coords: &[i64]) -> i64 {
        coords.iter().copied().max().unwrap_or(i64::MIN)
    }
    pub fn collapse_product(coords: &[i64]) -> i64 {
        coords.iter().product()
    }
    pub fn collapse_count(results: &[i64], sentinel: i64) -> usize {
        results.iter().filter(|&&v| v != sentinel).count()
    }
    pub fn collapse_weighted_sum(coords: &[i64], weights: &[i64]) -> i64 {
        coords.iter().zip(weights.iter()).map(|(c, w)| c * w).sum()
    }
    pub fn collapse_weighted_avg(coords: &[i64], weights: &[i64]) -> i64 {
        let ws: i64 = weights.iter().sum();
        if ws == 0 {
            return 0;
        }
        collapse_weighted_sum(coords, weights) / ws
    }

    // ── Field ──
    pub fn field_add_constraint(
        field: &mut [u8; 512],
        constraint_fn: usize,
        constraint_id: u32,
    ) -> i32 {
        let num = u32::from_le_bytes(field[480..484].try_into().unwrap());
        if num >= 8 {
            return -1;
        }
        let idx = num as usize;
        field[idx * 8..idx * 8 + 8].copy_from_slice(&constraint_fn.to_le_bytes());
        field[64 + idx * 4..64 + idx * 4 + 4].copy_from_slice(&constraint_id.to_le_bytes());
        field[480..484].copy_from_slice(&(num + 1).to_le_bytes());
        0
    }
    pub fn field_remove_constraint(field: &mut [u8; 512], constraint_id: u32) -> i32 {
        let num = u32::from_le_bytes(field[480..484].try_into().unwrap()) as usize;
        for i in 0..num {
            let id = u32::from_le_bytes(field[64 + i * 4..64 + i * 4 + 4].try_into().unwrap());
            if id == constraint_id {
                for j in i..num - 1 {
                    let src_fn =
                        usize::from_le_bytes(field[(j + 1) * 8..(j + 2) * 8].try_into().unwrap());
                    field[j * 8..j * 8 + 8].copy_from_slice(&src_fn.to_le_bytes());
                    let src_id = u32::from_le_bytes(
                        field[64 + (j + 1) * 4..64 + (j + 2) * 4]
                            .try_into()
                            .unwrap(),
                    );
                    field[64 + j * 4..64 + j * 4 + 4].copy_from_slice(&src_id.to_le_bytes());
                }
                field[480..484].copy_from_slice(&((num as u32) - 1).to_le_bytes());
                return 0;
            }
        }
        0
    }
    pub fn field_clear(field: &mut [u8; 512]) {
        field[480..488].copy_from_slice(&[0u8; 8]);
    }
    pub fn field_add_transition(
        field: &mut [u8; 512],
        from_id: i64,
        to_id: i64,
        weight: i64,
    ) -> i32 {
        let num = u32::from_le_bytes(field[484..488].try_into().unwrap());
        if num >= 16 {
            return -1;
        }
        let idx = num as usize;
        let base = 96 + idx * 24;
        field[base..base + 8].copy_from_slice(&from_id.to_le_bytes());
        field[base + 8..base + 16].copy_from_slice(&to_id.to_le_bytes());
        field[base + 16..base + 24].copy_from_slice(&weight.to_le_bytes());
        field[484..488].copy_from_slice(&(num + 1).to_le_bytes());
        0
    }
    pub fn field_update_weight(
        field: &mut [u8; 512],
        from_id: i64,
        to_id: i64,
        new_weight: i64,
    ) -> i32 {
        let num = u32::from_le_bytes(field[484..488].try_into().unwrap()) as usize;
        for i in 0..num {
            let base = 96 + i * 24;
            let fid = i64::from_le_bytes(field[base..base + 8].try_into().unwrap());
            let tid = i64::from_le_bytes(field[base + 8..base + 16].try_into().unwrap());
            if fid == from_id && tid == to_id {
                field[base + 16..base + 24].copy_from_slice(&new_weight.to_le_bytes());
                return 0;
            }
        }
        -1
    }
    pub fn field_get_transitions(field: &[u8; 512], from_id: i64) -> Vec<(i64, i64)> {
        let num = u32::from_le_bytes(field[484..488].try_into().unwrap()) as usize;
        let mut out = Vec::new();
        for i in 0..num {
            let base = 96 + i * 24;
            let fid = i64::from_le_bytes(field[base..base + 8].try_into().unwrap());
            if fid == from_id {
                let tid = i64::from_le_bytes(field[base + 8..base + 16].try_into().unwrap());
                let w = i64::from_le_bytes(field[base + 16..base + 24].try_into().unwrap());
                out.push((tid, w));
            }
        }
        out
    }

    // ── Layout ──    // ── Layout ──
    pub fn layout_linear_1d(coord: i64, stride: i64) -> i64 {
        coord * stride
    }
    pub fn layout_linear_nd(coords: &[i64], strides: &[i64]) -> i64 {
        coords.iter().zip(strides.iter()).map(|(c, s)| c * s).sum()
    }
    pub fn layout_row_major_2d(x: i64, y: i64, width: i64, elem_size: i64) -> i64 {
        (y * width + x) * elem_size
    }
    pub fn layout_col_major_2d(x: i64, y: i64, height: i64, elem_size: i64) -> i64 {
        (x * height + y) * elem_size
    }
    pub fn morton_encode_2d(x: u32, y: u32) -> u64 {
        fn spread(v: u32) -> u64 {
            let mut x = v as u64;
            x = (x | (x << 16)) & 0x0000FFFF0000FFFF;
            x = (x | (x << 8)) & 0x00FF00FF00FF00FF;
            x = (x | (x << 4)) & 0x0F0F0F0F0F0F0F0F;
            x = (x | (x << 2)) & 0x3333333333333333;
            x = (x | (x << 1)) & 0x5555555555555555;
            x
        }
        spread(x) | (spread(y) << 1)
    }

    // ── Adjacency ──
    pub fn adj_grid_4(
        x: i64,
        y: i64,
        min_x: i64,
        max_x: i64,
        min_y: i64,
        max_y: i64,
    ) -> Vec<(i64, i64)> {
        let mut r = Vec::with_capacity(4);
        if x + 1 <= max_x {
            r.push((x + 1, y));
        }
        if x - 1 >= min_x {
            r.push((x - 1, y));
        }
        if y + 1 <= max_y {
            r.push((x, y + 1));
        }
        if y - 1 >= min_y {
            r.push((x, y - 1));
        }
        r
    }
    pub fn adj_manhattan_1d(coord: i64, distance: u32, min_coord: i64, max_coord: i64) -> Vec<i64> {
        let mut r = Vec::new();
        for d in 1..=distance as i64 {
            let p = coord + d;
            if p <= max_coord {
                r.push(p);
            }
            let n = coord - d;
            if n >= min_coord {
                r.push(n);
            }
        }
        r
    }
    pub fn adj_graph_edges(edges: &[(i64, i64)], from_id: i64) -> Vec<i64> {
        edges
            .iter()
            .filter(|&&(f, _)| f == from_id)
            .map(|&(_, t)| t)
            .collect()
    }
}

// ============================================================================
// Tests — all platforms. Golden anchors prevent asm/rust drift.
// ============================================================================

#[cfg(test)]
mod tests {
    use super::REJECT_SENTINEL;

    // Read golden anchors from each assembly file.
    const ASM_OBSERVE_FULL: &str = include_str!("../asm/observe_full.S");
    const ASM_COLLAPSE: &str = include_str!("../asm/collapse.S");
    const ASM_FIELD_UPDATE: &str = include_str!("../asm/field_update.S");
    const ASM_SCHEME_LAYOUT: &str = include_str!("../asm/scheme_layout.S");
    const ASM_SCHEME_ADJACENCY: &str = include_str!("../asm/scheme_adjacency.S");

    fn parse_golden(src: &str, key: &str) -> Vec<i64> {
        for line in src.lines() {
            let t = line.trim();
            if let Some(val) = t.strip_prefix(&format!("# {}: ", key)) {
                return val
                    .split(',')
                    .map(|s| {
                        let s = s.trim();
                        if s == "REJECT" {
                            REJECT_SENTINEL
                        } else {
                            s.parse().unwrap()
                        }
                    })
                    .collect();
            }
        }
        panic!("GOLDEN anchor \"{}\" not found in assembly source", key);
    }

    // ── Observe golden anchors ──
    #[test]
    fn test_observe_golden_anchors() {
        let seg = parse_golden(ASM_OBSERVE_FULL, "GOLDEN_SEGMENTS");
        assert_eq!(seg, [2, 3, 5, 10, 12]);
        let narrow = parse_golden(ASM_OBSERVE_FULL, "GOLDEN_NARROW");
        assert_eq!(
            narrow,
            [2, REJECT_SENTINEL, REJECT_SENTINEL, 10, REJECT_SENTINEL]
        );
    }

    // ── Generated-table observe golden anchors ──
    // The assembly consumes SCHEME_SEG_COUNT / SCHEME_COORDS emitted by the
    // standard workspace emitter. The host fallback must reproduce the same
    // projections over the same generated structure, and the .S table data
    // (exposed by build.rs as asm_data) must agree with the anchors.
    #[cfg(not(target_arch = "riscv64"))]
    #[test]
    fn test_scheme_observe_golden_anchors() {
        use super::asm_data::observe_full as data;
        use super::fallback;

        let segs = parse_golden(ASM_OBSERVE_FULL, "GOLDEN_SCHEME_SEGMENTS");
        assert_eq!(segs, [2, 3, 5, 10, 12]);
        let narrow = parse_golden(ASM_OBSERVE_FULL, "GOLDEN_SCHEME_NARROW");
        let broad = parse_golden(ASM_OBSERVE_FULL, "GOLDEN_SCHEME_BROAD");

        // Cross-check the .S tables against the anchors: the generated
        // structure itself must carry the anchor values.
        assert_eq!(data::SCHEME_SEG_COUNT, 5);
        let table = [
            data::SEG_0,
            data::SEG_1,
            data::SEG_2,
            data::SEG_3,
            data::SEG_4,
        ];
        assert_eq!(table.as_slice(), segs.as_slice());

        let and_field = |v| fallback::compose_and(fallback::ck_even, fallback::ck_range_0_10, v);
        let or_field = |v| fallback::compose_or(fallback::ck_even, fallback::ck_range_0_10, v);

        let got_narrow: Vec<i64> = segs
            .iter()
            .map(|&v| fallback::observe(and_field, v, fallback::proj_id))
            .collect();
        let got_broad: Vec<i64> = segs
            .iter()
            .map(|&v| fallback::observe(or_field, v, fallback::proj_id))
            .collect();

        assert_eq!(got_narrow, narrow);
        assert_eq!(got_broad, broad);
    }

    // ── Collapse golden anchors ──
    #[test]
    fn test_collapse_golden_anchors() {
        assert_eq!(parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_SUM_A"), [20]);
        assert_eq!(parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_SUM_B"), [16]);
        assert_eq!(parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_MIN_A"), [2]);
        assert_eq!(parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_MAX_B"), [7]);
        assert_eq!(parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_PROD_A"), [384]);
        assert_eq!(parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_COUNT_A"), [4]);
        assert_eq!(
            parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_WEIGHTED_SUM_A"),
            [32]
        );
        assert_eq!(
            parse_golden(ASM_COLLAPSE, "GOLDEN_COLLAPSE_WEIGHTED_AVG_A"),
            [5]
        );
    }

    // ── Field update golden anchors ──
    #[test]
    fn test_field_update_golden_anchors() {
        assert_eq!(
            parse_golden(ASM_FIELD_UPDATE, "GOLDEN_FIELD_ADD_CONSTRAINT"),
            [0]
        );
        assert_eq!(
            parse_golden(ASM_FIELD_UPDATE, "GOLDEN_FIELD_REMOVE_CONSTRAINT"),
            [0]
        );
        assert_eq!(
            parse_golden(ASM_FIELD_UPDATE, "GOLDEN_FIELD_ADD_TRANSITION"),
            [0]
        );
        assert_eq!(
            parse_golden(ASM_FIELD_UPDATE, "GOLDEN_FIELD_UPDATE_WEIGHT"),
            [0]
        );
    }

    // ── Layout golden anchors ──
    #[test]
    fn test_layout_golden_anchors() {
        assert_eq!(
            parse_golden(ASM_SCHEME_LAYOUT, "GOLDEN_LAYOUT_LINEAR_1D"),
            [42]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_LAYOUT, "GOLDEN_LAYOUT_ROW_MAJOR_2D"),
            [42]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_LAYOUT, "GOLDEN_LAYOUT_COL_MAJOR_2D"),
            [34]
        );
        assert_eq!(parse_golden(ASM_SCHEME_LAYOUT, "GOLDEN_MORTON_2D"), [9]);
    }

    // ── Adjacency golden anchors ──
    #[test]
    fn test_adjacency_golden_anchors() {
        assert_eq!(
            parse_golden(ASM_SCHEME_ADJACENCY, "GOLDEN_ADJ_GRID_4_CENTER"),
            [4]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_ADJACENCY, "GOLDEN_ADJ_GRID_4_CORNER"),
            [2]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_ADJACENCY, "GOLDEN_ADJ_GRID_8_CENTER"),
            [8]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_ADJACENCY, "GOLDEN_ADJ_GRID_8_CORNER"),
            [3]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_ADJACENCY, "GOLDEN_ADJ_MANHATTAN_1D_D1"),
            [2]
        );
        assert_eq!(
            parse_golden(ASM_SCHEME_ADJACENCY, "GOLDEN_ADJ_MANHATTAN_1D_D2"),
            [4]
        );
    }

    // ── Fallback tests ──
    #[cfg(not(target_arch = "riscv64"))]
    mod fallback_tests {
        use super::super::fallback;

        // Observe
        #[test]
        fn test_observe_fallback() {
            assert_eq!(fallback::ck_even(2), 1);
            assert_eq!(fallback::ck_even(3), 0);
            assert_eq!(fallback::ck_range_0_10(5), 1);
            assert_eq!(fallback::ck_range_0_10(11), 0);
            let narrow = |v| fallback::compose_and(fallback::ck_even, fallback::ck_range_0_10, v);
            assert_eq!(fallback::observe(narrow, 2, fallback::proj_id), 2);
            assert_eq!(
                fallback::observe(narrow, 3, fallback::proj_id),
                crate::ssccs_asm::REJECT_SENTINEL
            );
        }

        // Collapse
        #[test]
        fn test_collapse_fallback() {
            assert_eq!(fallback::collapse_sum(&[2, 4, 6, 8]), 20);
            assert_eq!(fallback::collapse_sum(&[1, 3, 5, 7]), 16);
            assert_eq!(fallback::collapse_min(&[2, 4, 6, 8]), 2);
            assert_eq!(fallback::collapse_max(&[1, 3, 5, 7]), 7);
            assert_eq!(fallback::collapse_product(&[2, 4, 6, 8]), 384);
            assert_eq!(fallback::collapse_count(&[2, -1, 6, -1], -1), 2);
            assert_eq!(
                fallback::collapse_weighted_sum(&[2, 4, 6, 8], &[1, 2, 1, 2]),
                32
            );
            assert_eq!(
                fallback::collapse_weighted_avg(&[2, 4, 6, 8], &[1, 2, 1, 2]),
                5
            );
        }

        // Layout
        #[test]
        fn test_layout_fallback() {
            assert_eq!(fallback::layout_linear_1d(42, 1), 42);
            assert_eq!(fallback::layout_row_major_2d(2, 5, 8, 1), 42);
            assert_eq!(fallback::layout_col_major_2d(2, 5, 6, 1), 17); // 2*6+5 = 17, not 34
                                                                       // Actually 34 is (2*6+5)*2 with elem=2, let me adjust
                                                                       // 34 = (2*6+5)*2 = 34, so elem_size = 2
            assert_eq!(fallback::layout_col_major_2d(2, 5, 6, 2), 34);
            // Morton(1, 2) = 9
            assert_eq!(fallback::morton_encode_2d(1, 2), 9);
        }

        // Adjacency
        #[test]
        fn test_adjacency_fallback() {
            let center = fallback::adj_grid_4(2, 2, 0, 4, 0, 4);
            assert_eq!(center.len(), 4);
            let corner = fallback::adj_grid_4(0, 0, 0, 4, 0, 4);
            assert_eq!(corner.len(), 2);
            let d1 = fallback::adj_manhattan_1d(5, 1, 0, 10);
            assert_eq!(d1.len(), 2);
            let d2 = fallback::adj_manhattan_1d(5, 2, 0, 10);
            assert_eq!(d2.len(), 4);
            let edges = fallback::adj_graph_edges(&[(0, 1), (0, 2), (1, 3)], 0);
            assert_eq!(edges, vec![1, 2]);
        }

        // Field
        #[test]
        fn test_field_fallback() {
            let mut field = [0u8; 512];
            assert_eq!(fallback::field_add_constraint(&mut field, 0x1000, 1), 0);
            assert_eq!(fallback::field_add_constraint(&mut field, 0x2000, 2), 0);
            assert_eq!(u32::from_le_bytes(field[480..484].try_into().unwrap()), 2);

            // Transitions
            assert_eq!(fallback::field_add_transition(&mut field, 10, 20, 100), 0);
            let trans = fallback::field_get_transitions(&field, 10);
            assert_eq!(trans.len(), 1);
            assert_eq!(trans[0], (20, 100));

            // Update weight
            assert_eq!(fallback::field_update_weight(&mut field, 10, 20, 200), 0);
            let trans = fallback::field_get_transitions(&field, 10);
            assert_eq!(trans[0].1, 200);

            // Remove constraint
            assert_eq!(fallback::field_remove_constraint(&mut field, 1), 0);
            assert_eq!(u32::from_le_bytes(field[480..484].try_into().unwrap()), 1);

            // Clear
            fallback::field_clear(&mut field);
            assert_eq!(u32::from_le_bytes(field[480..484].try_into().unwrap()), 0);
            assert_eq!(u32::from_le_bytes(field[484..488].try_into().unwrap()), 0);
        }
    }
}

// Include auto-generated constants from asm/*.S (via build.rs)
include!(concat!(env!("OUT_DIR"), "/asm_data.rs"));
