//! Hardware mapping for SSCCS Field composition patterns.
//!
//! Maps abstract Field composition operators to concrete hardware primitives.
//! These mappings were validated by nex-calc's FIH-based calculator, which
//! proved that operator-level composition (Compose, Product, Intersect)
//! naturally maps to hardware dataflow patterns.
//!
//! # Mapping Table
//!
//! | Field Pattern    | Hardware Primitive    | nex-calc Analog              |
//! |------------------|-----------------------|------------------------------|
//! | Compose (A∘B)    | Pipeline register     | resolve(A) → Fact → resolve(B) |
//! | Product (A⊗B)    | Parallel LUT/DSP      | Two Intents resolved independently |
//! | Intersect (C?A:B)| Comparator + MUX      | Hint-gated resolution         |
//! | Union (A∪B)      | OR gate (admissibility)| Constraint union              |
//! | Intersection (A∩B)| AND gate              | Multi-constraint check        |

pub use ssccs_core::{Coordinates, Segment};

/// Hardware target for synthesis.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HardwareTarget {
    /// FPGA synthesis: LUT, DSP, block RAM, routing fabric.
    FPGA,
    /// ASIC synthesis: standard cells, hard macros.
    ASIC,
    /// RISC-V custom instruction (XIF coprocessor).
    RISCV,
    /// SystemVerilog module generation.
    SystemVerilog,
}

/// Hardware primitive generated by a composition pattern.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HardwarePrimitive {
    /// Pipeline stage: register → combinational logic → register.
    Pipeline {
        stages: usize,
        latency_cycles: usize,
    },
    /// Parallel execution: independent hardware blocks.
    Parallel { units: usize, independent: bool },
    /// Multiplexer: condition selects between two paths.
    Mux {
        comparison: String,
        true_path: Box<HardwarePrimitive>,
        false_path: Box<HardwarePrimitive>,
    },
    /// Combinational gate: AND, OR, XOR applied to admissibility signals.
    Gate { gate_type: String, inputs: usize },
    /// Direct wire connection between hardware primitives.
    Wire { from: String, to: String },
}

/// Map a compose pattern to a pipeline primitive.
pub fn compose_to_pipeline(stages: usize) -> HardwarePrimitive {
    HardwarePrimitive::Pipeline {
        stages,
        latency_cycles: stages,
    }
}

/// Map a product pattern to parallel hardware.
pub fn product_to_parallel(units: usize) -> HardwarePrimitive {
    HardwarePrimitive::Parallel {
        units,
        independent: true,
    }
}

/// Map an intersect pattern to a MUX.
pub fn intersect_to_mux(
    condition: &str,
    true_path: HardwarePrimitive,
    false_path: HardwarePrimitive,
) -> HardwarePrimitive {
    HardwarePrimitive::Mux {
        comparison: condition.to_string(),
        true_path: Box::new(true_path),
        false_path: Box::new(false_path),
    }
}

/// Map constraint union to an OR gate.
pub fn union_to_or(inputs: usize) -> HardwarePrimitive {
    HardwarePrimitive::Gate {
        gate_type: "OR".into(),
        inputs,
    }
}

/// Map constraint intersection to an AND gate.
pub fn intersection_to_and(inputs: usize) -> HardwarePrimitive {
    HardwarePrimitive::Gate {
        gate_type: "AND".into(),
        inputs,
    }
}

/// Generate SystemVerilog for a compose pipeline.
pub fn generate_pipeline_sv(stages: usize, op_a: &str, op_b: &str) -> String {
    let mut sv = String::new();
    sv.push_str("// Auto-generated pipeline: ComposeField\n");
    sv.push_str("// Maps: compose(A, B) → pipeline(op_a → op_b)\n");
    sv.push_str(&format!(
        "// Stages: {stages}, Operations: {op_a} → {op_b}\n\n"
    ));
    sv.push_str("module compose_pipeline (\n");
    sv.push_str("    input  wire clk,\n");
    sv.push_str("    input  wire rst_n,\n");
    sv.push_str("    input  wire [63:0] operand_a,\n");
    sv.push_str("    input  wire [63:0] operand_b,\n");
    sv.push_str("    output wire [63:0] result\n");
    sv.push_str(");\n\n");
    for i in 1..=stages {
        sv.push_str(&format!("    reg [63:0] stage_{i}_reg;\n"));
    }
    sv.push_str(&format!("\n    // Stage 1: {op_a}\n"));
    sv.push_str(&format!("    // (implementation depends on {op_a})\n"));
    if stages > 1 {
        sv.push_str(&format!("\n    // Stage 2: {op_b}\n"));
        sv.push_str(&format!("    // (implementation depends on {op_b})\n"));
    }
    sv.push_str("\nendmodule\n");
    sv
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compose_generates_pipeline() {
        let p = compose_to_pipeline(2);
        assert!(matches!(p, HardwarePrimitive::Pipeline { stages: 2, .. }));
    }

    #[test]
    fn test_product_generates_parallel() {
        let p = product_to_parallel(2);
        assert!(matches!(
            p,
            HardwarePrimitive::Parallel {
                units: 2,
                independent: true
            }
        ));
    }

    #[test]
    fn test_intersect_generates_mux() {
        let p = intersect_to_mux(
            "x > 10",
            HardwarePrimitive::Pipeline {
                stages: 1,
                latency_cycles: 1,
            },
            HardwarePrimitive::Pipeline {
                stages: 1,
                latency_cycles: 1,
            },
        );
        assert!(matches!(p, HardwarePrimitive::Mux { .. }));
    }

    #[test]
    fn test_sv_generation() {
        let sv = generate_pipeline_sv(2, "add", "mul");
        assert!(sv.contains("compose_pipeline"));
        assert!(sv.contains("stage_1_reg"));
        assert!(sv.contains("stage_2_reg"));
    }
}
