"""
SV Architecture Diagram Loader
==============================
Provides `load_sv_dot()` — loads auto-generated SV architecture DOT
from _include/sv_architecture.dot (generated by build.yml pre_build).

Usage in QMD:
  ```{python}
  #| include: false
  #| context: local
  %run ../../../../_include/_sv_diagram.py
  ```

  ```{python}
  #| label: fig-sv-architecture
  #| fig-cap: "SV module architecture"
  from _graphviz import dot
  d = load_sv_dot()
  if d:
      dot(d, h="400px")
  ```
"""

import os


def load_sv_dot(path: str = None) -> str:
    if path is None:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        path = os.path.join(script_dir, "sv_architecture.dot")
    try:
        with open(path) as f:
            return f.read()
    except FileNotFoundError:
        return ""
