[package]
name = "ssccs-field-synthesis"
version = "0.1.0"
edition = "2024"

[dependencies]
ssccs-core = { path = "../core" }
ssccs-primitive = { path = "../primitive", optional = true }
blake3 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
thiserror = { workspace = true }
dyn-clone = { workspace = true }
