# docs/_quarto.yml
# Common configuration for all SSCCS documentation
# Documents may override these settings in their own frontmatter.

# Shared bibliography and citation style
csl: _include/ieee.csl
link-citations: true

# Global format defaults
format:
  html:
    number-sections: false
    default-figure-format: "svg"
    fig-format: "svg"
    embed-resources: true
    self-contained-math: true
    minimal: true
    theme: minimal
    toc: true
    toc-title: "Contents"
    toc-expand: true
    font-size: 11pt
    page-layout: full
    code-overflow: wrap
    include-in-header:
      file: ./_include/default_html_style.txt
    format-links: false
    execute:
        eval: true
        echo: false

  gfm:
    number-sections: false
  pdf:
    number-sections: false
    default-figure-format: "pdf"
    fig-format: pdf
    fig-dpi: 300    
    papersize: a4
    graphics: true
    highlight-style: monochrome
    fig-pos: 'H'
    fig-cap-location: bottom
    mainfont: LibertinusSerif-Regular.otf
    mainfontoptions:
      - BoldFont=LibertinusSerif-Bold.otf
      - ItalicFont=LibertinusSerif-Italic.otf
      - BoldItalicFont=LibertinusSerif-BoldItalic.otf

  beamer:
    number-sections: false
    fig-format: pdf
    aspectratio: 1610
    classoption: [12pt]
    fonttheme: "professionalfonts"