# docs/_quarto.yml
# Common configuration for all SSCCS documentation
# Documents may override these settings in their own frontmatter.

# Shared
author:
  - name: SSCCS Foundation
    corresponding: true 
    email: contact@ssccs.org
    affiliations:
      - name: SSCCS Foundation
        domain: ssccs.org
        url: https://ssccs.org
csl: _include/ieee.csl
link-citations: true