#!/usr/bin/env python3
"""
Generate a hierarchical llms.txt from the _site directory structure.

Walks the _site directory to discover .llms.md files, groups them by their
directory hierarchy, extracts titles from YAML frontmatter, and produces a
structured markdown file that replaces the flat llms.txt generated by Quarto.

Output is written to _site/llms.txt and _llms/llms.txt (if it exists).

Usage:
    python3 _utils/generate_llms_txt.py [--site-dir PATH] [--base-url URL]
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def extract_title_from_file(filepath: Path) -> str:
    """
    Extract the title from a .llms.md file.

    Tries YAML frontmatter first, then falls back to the first Markdown
    heading (# Title), and finally to the filename stem.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return filepath.stem

    # Try YAML frontmatter
    frontmatter_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if frontmatter_match:
        frontmatter = frontmatter_match.group(1)
        title_match = re.search(r"^title:\s*['\"]?(.+?)['\"]?\s*$", frontmatter, re.MULTILINE)
        if title_match:
            return title_match.group(1).strip()

    # Fall back to first Markdown heading
    heading_match = re.search(r"^#\s+(.+?)$", content, re.MULTILINE)
    if heading_match:
        return heading_match.group(1).strip()

    return filepath.stem


def build_tree(site_dir: Path, base_url: str) -> Dict[str, List[Tuple[str, str]]]:
    """
    Walk _site directory and build a hierarchical tree of .llms.md files.

    Returns a dict mapping directory path (relative to site_dir) to a list of
    (title, url) tuples. The key '' represents the root of site_dir.
    """
    tree: Dict[str, List[Tuple[str, str]]] = {}

    for llms_file in sorted(site_dir.rglob("*.llms.md")):
        rel_path = llms_file.relative_to(site_dir)
        # Directory part relative to site_dir, or '' for root
        dir_key = str(rel_path.parent) if str(rel_path.parent) != "." else ""

        # Build URL from relative path
        url = f"{base_url}/{rel_path}"

        title = extract_title_from_file(llms_file)

        if dir_key not in tree:
            tree[dir_key] = []
        tree[dir_key].append((title, url))

    return tree


def get_sorted_tree_keys(tree: Dict[str, List[Tuple[str, str]]]) -> List[str]:
    """
    Sort tree keys so that root ('') comes first, then top-level dirs,
    then nested dirs in depth-first order.
    """
    keys = list(tree.keys())

    def sort_key(k: str) -> Tuple[int, str]:
        if k == "":
            return (0, "")
        depth = k.count("/")
        return (depth + 1, k)

    return sorted(keys, key=sort_key)


def generate_llms_txt(tree: Dict[str, List[Tuple[str, str]]], site_dir: Path) -> str:
    """
    Generate hierarchical llms.txt content from the tree.

    Root-level pages are grouped under "## Root".
    Each directory gets a "## DirName" heading.
    Nested directories receive additional "#" characters per depth level.
    """
    lines: List[str] = []
    lines.append("# SSCCS Documentation")
    lines.append("")

    sorted_keys = get_sorted_tree_keys(tree)

    for dir_key in sorted_keys:
        entries = tree[dir_key]
        # Sort entries alphabetically by title within each directory group
        entries.sort(key=lambda x: x[0].lower())

        if dir_key == "":
            # Root-level pages
            lines.append("## Root")
        else:
            # Directory heading: depth determines heading level
            depth = dir_key.count("/") + 1
            # Use the full relative path as the section name for unambiguous hierarchy
            heading_prefix = "#" * min(depth + 1, 6)  # Cap at ######
            lines.append(f"{heading_prefix} {dir_key}")

        lines.append("")
        for title, url in entries:
            lines.append(f"- [{title}]({url})")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hierarchical llms.txt from _site directory structure"
    )
    parser.add_argument(
        "--site-dir",
        type=Path,
        default=None,
        help="Path to _site directory (default: ../_site relative to this script)",
    )
    parser.add_argument(
        "--base-url",
        type=str,
        default="https://docs.ssccs.org",
        help="Base URL for constructing links (default: https://docs.ssccs.org)",
    )
    args = parser.parse_args()

    base_url = args.base_url.rstrip("/")

    # Determine docs root and _site path
    script_dir = Path(__file__).parent.resolve()
    docs_root = script_dir.parent

    site_dir = args.site_dir if args.site_dir else (docs_root / "_site")

    if not site_dir.exists() or not site_dir.is_dir():
        print(f"Site directory not found: {site_dir}", file=sys.stderr)
        sys.exit(1)

    # Build the hierarchical tree
    tree = build_tree(site_dir, base_url)

    if not tree:
        print("No .llms.md files found in _site directory.", file=sys.stderr)
        # Still write an empty-ish llms.txt
        content = "# SSCCS Documentation\n\n## Pages\n\n"
    else:
        content = generate_llms_txt(tree, site_dir)

    # Write to _site/llms.txt
    output_path = site_dir / "llms.txt"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated {output_path} with {sum(len(v) for v in tree.values())} entries across {len(tree)} sections")

    # Also write to _llms/llms.txt if it exists
    llms_dir = docs_root / "_llms"
    if llms_dir.exists() and llms_dir.is_dir():
        llms_output = llms_dir / "llms.txt"
        with open(llms_output, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Copied to {llms_output}")


if __name__ == "__main__":
    main()
