#!/usr/bin/env python3
"""
Generate a hierarchical llms.txt from the _llms directory structure.

Walks the _llms directory (rsynced LLM-friendly output) recursively to
discover .llms.md files, groups them by directory hierarchy, extracts
titles from Markdown headings, and produces a structured markdown file
that replaces the flat llms.txt generated by Quarto.

Writes only to _llms/llms.txt.

Usage:
    python3 _utils/generate_llms_txt.py [--base-url URL]
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple


def extract_title_from_file(filepath: Path) -> str:
    """
    Extract the title from a .llms.md file.

    Tries YAML frontmatter first, then falls back to the first Markdown
    heading (# Title), and finally to the filename stem.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return filepath.stem

    frontmatter_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if frontmatter_match:
        frontmatter = frontmatter_match.group(1)
        title_match = re.search(
            r"^title:\s*['\"]?(.+?)['\"]?\s*$", frontmatter, re.MULTILINE
        )
        if title_match:
            return title_match.group(1).strip()

    heading_match = re.search(r"^#\s+(.+?)$", content, re.MULTILINE)
    if heading_match:
        return heading_match.group(1).strip()

    return filepath.stem


def get_sorted_tree_keys(
    tree: Dict[str, List[Tuple[str, str]]],
) -> List[str]:
    """
    Sort tree keys so root ('') comes first, then top-level dirs,
    then nested dirs sorted by depth then path.
    """
    keys = list(tree.keys())

    def sort_key(k: str) -> Tuple[int, str]:
        if k == "":
            return (0, "")
        depth = k.count("/")
        return (depth + 1, k)

    return sorted(keys, key=sort_key)


def generate_llms_txt(tree: Dict[str, List[Tuple[str, str]]]) -> str:
    """
    Generate hierarchical llms.txt content from the tree.

    Root-level pages are grouped under "## Root".
    Each directory gets a heading at the appropriate level keyed by its
    full relative path for unambiguous hierarchy.
    """
    lines: list[str] = []
    lines.append("# SSCCS Documentation")
    lines.append("")

    for dir_key in get_sorted_tree_keys(tree):
        entries = tree[dir_key]
        entries.sort(key=lambda x: x[0].lower())

        if dir_key == "":
            lines.append("## Root")
        else:
            depth = dir_key.count("/") + 1
            heading_prefix = "#" * min(depth + 1, 6)
            lines.append(f"{heading_prefix} {dir_key}")

        lines.append("")
        for title, url in entries:
            lines.append(f"- [{title}]({url})")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hierarchical llms.txt from _llms directory structure"
    )
    parser.add_argument(
        "--base-url",
        type=str,
        default="https://docs.ssccs.org",
        help="Base URL for constructing links (default: https://docs.ssccs.org)",
    )
    args = parser.parse_args()

    base_url = args.base_url.rstrip("/")

    script_dir = Path(__file__).parent.resolve()
    docs_root = script_dir.parent
    llms_dir = docs_root / "_llms"

    if not llms_dir.exists() or not llms_dir.is_dir():
        # _llms does not exist; this is expected in non-website mode.
        # Skip gracefully without error.
        print(f"_llms directory not found at {llms_dir}, skipping.")
        sys.exit(0)

    tree: Dict[str, List[Tuple[str, str]]] = {}
    for llms_file in sorted(llms_dir.rglob("*.llms.md")):
        rel_path = llms_file.relative_to(llms_dir)
        dir_key = str(rel_path.parent) if str(rel_path.parent) != "." else ""
        url = f"{base_url}/{rel_path}"
        title = extract_title_from_file(llms_file)
        if dir_key not in tree:
            tree[dir_key] = []
        tree[dir_key].append((title, url))

    if not tree:
        print(f"No .llms.md files found in {llms_dir}.", file=sys.stderr)
        content = "# SSCCS Documentation\n\n## Pages\n\n"
    else:
        content = generate_llms_txt(tree)

    llms_txt_path = llms_dir / "llms.txt"
    with open(llms_txt_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(
        f"Generated {llms_txt_path} with {sum(len(v) for v in tree.values())} "
        f"entries across {len(tree)} sections"
    )


if __name__ == "__main__":
    main()
