name: Check Dockerfiles

on:
  push:
    branches: [develop, main]
    paths:
      - '.devcontainer/**/*.json'
      - '.devcontainer/**/*.sh'
      - '.github/workflows/check-dockerfiles.yml'
      - '**/Dockerfile'
  pull_request:
    branches: [develop, main]
    paths:
      - '.devcontainer/**/*.json'
      - '.devcontainer/**/*.sh'
      - '.github/workflows/check-dockerfiles.yml'
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docs/Dockerfile
          tags: dockerimg-docs
          load: true
          cache-from: type=gha,scope=shared-docs
          cache-to: type=gha,mode=min,scope=shared-docs

      - name: Validate environment
        run: |
          docker run --rm dockerimg-docs \
            bash -c "python --version && c2patool --version && lualatex --version && quarto check && echo 'All tools OK'"