# Workflow for building Quarto site with Python and deploying to GitHub Pages
name: Build and Deploy Quarto site

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**/*.py'
      - 'docs/**/*.qmd'
      - 'docs/**/*.md'
      - 'docs/**/*.yml'
      - 'docs/**/*.txt'
      - 'docs/**/*.svg'
      - 'docs/**/*.bib'
      - 'docs/**/*.csl'
      - 'docs/**/*.c2pa_manifest.json'
      - '.github/workflows/deploy-quarto-ghpage.yml'
      - '!docs/**/README.md'
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - 'docs/**/*.py'
      - 'docs/**/*.qmd'
      - 'docs/**/*.md'
      - 'docs/**/*.yml'
      - 'docs/**/*.txt'
      - 'docs/**/*.svg'
      - 'docs/**/*.bib'
      - 'docs/**/*.csl'
      - 'docs/**/*.c2pa_manifest.json'
      - '.github/workflows/deploy-quarto-ghpage.yml'
      - '!docs/**/README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: python docs/build.py --website
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_site

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4