name: Devcontainer Check

on:
  push:
    branches: [develop, main]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/verify-devcontainer.yml'
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/verify-devcontainer.yml'
  workflow_dispatch:
    inputs:
      test_scope:
        required: true
        default: 'all'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Run Validation
        uses: devcontainers/ci@v0.3
        with:
          imageName: ssccs-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            set -e
            quarto --version
            python --version
            c2patool --version
            echo "Environment Validation Complete"